### PR TITLE
Fix modals

### LINKED ISSUE #44: Fix Modal Styling

### PR DESCRIPTION
**Pull request by hTrap**
Fixes #44 
- Other style/color fixes

### CODE REVIEW

File: src/ui/components/argit/Sponsor.tsx [hunk 1]
```diff
@@ -11,15 +11,16 @@ export const Sponsor = connector(
     closeSponsorModal: actions.argit.closeSponsorModal
   })
 )(function SponsorImpl(props) {
-  const { address, repo } = props
+  console.log(props)
```
Comment (faza) [inline src/ui/components/argit/Sponsor.tsx:14]: Remove log

**Review by faza — CHANGES_REQUESTED** [review]

**Comment by faza** [comment]
Screenshot_2020-10-12_17-57-03
@hTrap In sponsor modal, address is flowing out of the modal window
